# AutomatedWorkflow Workflow
# Generated by restack-gen on 2025-11-13

from datetime import timedelta
from pydantic import BaseModel
from restack_ai.workflow import workflow, import_functions, log

with import_functions():
    from src.functions.llm_chat import llm_chat, LlmChatInput

class AutomatedWorkflowWorkflowInput(BaseModel):
    subject: str
    body: str

@workflow.defn()
class AutomatedWorkflowWorkflow:
    """AutomatedWorkflow workflow for testapp."""

    @workflow.run
    async def run(self, workflow_input: AutomatedWorkflowWorkflowInput):
        """Run the automated_workflow workflow."""
        log.info("AutomatedWorkflowWorkflow starting", input=workflow_input)

        # Workflow logic here - can call functions and agents
        result = {
            "message": "Hello from AutomatedWorkflowWorkflow",
            "input": workflow_input,
            "workflow": "AutomatedWorkflow"
        }

        log.info("AutomatedWorkflowWorkflow completed", result=result)
        return result


if __name__ == "__main__":
    # For local development
    import asyncio

    async def main():
        workflow_info()
        workflow_instance = AutomatedWorkflowWorkflow()
        result = await workflow_instance.run({"test": True})
        print(f"Workflow result: {result}")

    asyncio.run(main())